import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
  tArray: (key: string) => string[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Traduções
const translations = {
  pt: {
    // Login
    'login.title': 'Login',
    'login.welcome': 'Bem-vindo de volta',
    'login.subtitle': 'Entre com suas credenciais para continuar',
    'login.email': 'Email',
    'login.password': 'Senha',
    'login.emailPlaceholder': 'seu@email.com',
    'login.passwordPlaceholder': '••••••••',
    'login.forgotPassword': 'Esqueci minha senha',
    'login.submit': 'Entrar',
    'login.submitting': 'Entrando...',
    'login.noAccount': 'Não tem uma conta?',
    'login.signUp': 'Cadastre-se',
    // Sign Up
    'signup.title': 'Criar conta',
    'signup.subtitle': 'Preencha os dados abaixo para criar sua conta',
    'signup.name': 'Nome completo',
    'signup.namePlaceholder': 'Seu nome completo',
    'signup.confirmPassword': 'Confirmar senha',
    'signup.confirmPasswordPlaceholder': 'Digite a senha novamente',
    'signup.terms': 'Eu aceito os',
    'signup.termsOfUse': 'termos de uso',
    'signup.and': 'e',
    'signup.privacyPolicy': 'política de privacidade',
    'signup.submit': 'Criar conta',
    'signup.submitting': 'Criando conta...',
    'signup.hasAccount': 'Já tem uma conta?',
    'signup.signIn': 'Entrar',
    // Validation
    'validation.emailRequired': 'Email é obrigatório',
    'validation.emailInvalid': 'Email inválido',
    'validation.passwordRequired': 'Senha é obrigatória',
    'validation.passwordMinLength': 'Senha deve ter no mínimo 6 caracteres',
    'validation.nameRequired': 'Nome é obrigatório',
    'validation.nameMinLength': 'Nome deve ter no mínimo 3 caracteres',
    'validation.confirmPasswordRequired': 'Confirmação de senha é obrigatória',
    'validation.passwordsNotMatch': 'As senhas não coincidem',
    'validation.termsRequired': 'Você deve aceitar os termos de uso',
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Bem-vindo, {name}!',
    'dashboard.email': 'Email',
    'dashboard.logout': 'Sair',
    'dashboard.successMessage': 'Você está logado com sucesso. Esta é uma página de exemplo do dashboard.',
    // Menu
    'menu.home': 'Início',
    'menu.connectionManager': 'Instâncias',
    'menu.dispatches': 'Disparos',
    'menu.crm': 'CRM',
    'menu.mindClerky': 'MindClerky',
    'menu.integration': 'Integração',
    'menu.aiAgent': 'Agente de IA',
    'menu.documentation': 'Documentação',
    'menu.settings': 'Configurações',
    'menu.logout': 'Sair',
    // Common
    'common.appName': 'Clerky',
    'common.comingSoon': 'Em breve...',
    'common.loading': 'Carregando...',
    // CRM
    'crm.searchContacts': 'Buscar contatos...',
    'crm.dragContactsHere': 'Arraste contatos aqui',
    'crm.contact': 'contato',
    'crm.contacts': 'contatos',
    // Settings
    'settings.title': 'Configurações',
    'settings.profile': 'Perfil',
    'settings.profilePicture': 'Foto de Perfil',
    'settings.changePicture': 'Alterar Foto',
    'settings.removePicture': 'Remover Foto',
    'settings.name': 'Nome',
    'settings.namePlaceholder': 'Seu nome completo',
    'settings.email': 'Email',
    'settings.companyName': 'Nome da Empresa',
    'settings.companyNamePlaceholder': 'Nome da sua empresa',
    'settings.phone': 'Telefone',
    'settings.phonePlaceholder': '(DDD) 9 9999-9999',
    'settings.saveProfile': 'Salvar Perfil',
    'settings.saving': 'Salvando...',
    'settings.profileUpdated': 'Perfil atualizado com sucesso!',
    'settings.password': 'Senha',
    'settings.changePassword': 'Alterar Senha',
    'settings.currentPassword': 'Senha Atual',
    'settings.currentPasswordPlaceholder': 'Digite sua senha atual',
    'settings.newPassword': 'Nova Senha',
    'settings.newPasswordPlaceholder': 'Digite a nova senha',
    'settings.confirmNewPassword': 'Confirmar Nova Senha',
    'settings.confirmNewPasswordPlaceholder': 'Digite a nova senha novamente',
    'settings.updatePassword': 'Atualizar Senha',
    'settings.updating': 'Atualizando...',
    'settings.passwordUpdated': 'Senha alterada com sucesso!',
    'settings.selectImage': 'Selecionar Imagem',
    'settings.imageTooLarge': 'A imagem deve ter no máximo 2MB',
    'settings.invalidImageFormat': 'Formato de imagem inválido. Use JPG, PNG ou GIF',
    'settings.cropImage': 'Recortar Imagem',
    'settings.cropInstructions': 'Arraste para mover a área de recorte. Use os controles para zoom e rotação.',
    'settings.applyCrop': 'Aplicar Recorte',
    'settings.zoomIn': 'Aumentar Zoom',
    'settings.zoomOut': 'Diminuir Zoom',
    'settings.rotateLeft': 'Girar para Esquerda',
    'settings.rotateRight': 'Girar para Direita',
    'settings.preview': 'Preview',
    'common.cancel': 'Cancelar',
    // Errors
    'error.loginFailed': 'Erro ao fazer login. Verifique suas credenciais.',
    'error.registerFailed': 'Erro ao criar conta. Tente novamente.',
    'error.formProcessing': 'Erro ao processar formulário',
    'error.requestFailed': 'Erro ao processar requisição. Tente novamente.',
    'error.updateProfileFailed': 'Erro ao atualizar perfil. Tente novamente.',
    'error.changePasswordFailed': 'Erro ao alterar senha. Verifique os dados e tente novamente.',
    'error.getInstancesFailed': 'Erro ao buscar instâncias. Tente novamente.',
    'error.createInstanceFailed': 'Erro ao criar instância. Tente novamente.',
    'error.deleteInstanceFailed': 'Erro ao deletar instância. Tente novamente.',
    'error.updateSettingsFailed': 'Erro ao atualizar configurações. Tente novamente.',
    // Instances
    'instances.title': 'Instâncias WhatsApp',
    'instances.create': 'Criar Instância',
    'instances.createNew': 'Criar Nova Instância',
    'instances.createButton': 'Criar',
    'instances.creating': 'Criando...',
    'instances.cancel': 'Cancelar',
    'instances.name': 'Nome',
    'instances.instanceName': 'Nome da Instância',
    'instances.instanceNamePlaceholder': 'Ex: WhatsApp Pessoal, WhatsApp Empresa...',
    'instances.instanceNameHelp': 'Escolha um nome para identificar esta instância (mínimo 3 caracteres)',
    'instances.internalName': 'Nome Interno',
    'instances.qrcode': 'QR Code',
    'instances.settings': 'Configurações',
    'instances.updateSettings': 'Atualizar Configurações',
    'instances.updateButton': 'Atualizar',
    'instances.updating': 'Atualizando...',
    'instances.checkStatus': 'Verificar Status',
    'instances.delete': 'Deletar',
    'instances.deleteConfirm': 'Tem certeza que deseja deletar esta instância?',
    'instances.deleteSuccess': 'Instância deletada com sucesso!',
    'instances.createSuccess': 'Instância criada com sucesso!',
    'instances.settingsUpdated': 'Configurações atualizadas com sucesso!',
    'instances.statusChecked': 'Status verificado!',
    'instances.noInstances': 'Nenhuma instância encontrada',
    'instances.noInstancesDescription': 'Crie sua primeira instância WhatsApp para começar.',
    'instances.scanQRCode': 'Escaneie o QR Code com seu WhatsApp',
    'instances.qrCodeAutoClose': 'O modal será fechado automaticamente quando a conexão for estabelecida.',
    'instances.connectedSuccess': 'Instância conectada com sucesso!',
    'instances.rejectCall': 'Rejeitar chamadas',
    'instances.groupsIgnore': 'Ignorar grupos',
    'instances.alwaysOnline': 'Manter sempre online',
    'instances.readMessages': 'Marcar mensagens como lidas',
    'instances.readStatus': 'Ler status',
    'instances.syncFullHistory': 'Sincronizar histórico completo',
    'instances.created': 'Criada',
    'instances.connecting': 'Conectando',
    'instances.connected': 'Conectada',
    'instances.disconnected': 'Desconectada',
    'instances.error': 'Erro',
    // Dispatches
    'dispatches.title': 'Disparos',
    'dispatches.subtitle': 'Gerencie templates e disparos de mensagens em massa',
    'dispatches.templates': 'Templates',
    'dispatches.dispatches': 'Disparos',
    'dispatches.createTemplate': 'Criar Template',
    'dispatches.createFirstTemplate': 'Criar Primeiro Template',
    'dispatches.createDispatch': 'Criar Disparo',
    'dispatches.createFirstDispatch': 'Criar Primeiro Disparo',
    'dispatches.myTemplates': 'Meus Templates',
    'dispatches.myDispatches': 'Meus Disparos',
    'dispatches.noTemplates': 'Nenhum template criado ainda',
    'dispatches.noDispatches': 'Nenhum disparo criado ainda',
    'dispatches.loadingTemplates': 'Carregando templates...',
    'dispatches.loadingDispatches': 'Carregando disparos...',
    'dispatches.type': 'Tipo',
    'dispatches.edit': 'Editar',
    'dispatches.delete': 'Deletar',
    'dispatches.pause': 'Pausar',
    'dispatches.resume': 'Retomar',
    'dispatches.start': 'Iniciar',
    'dispatches.status': 'Status',
    'dispatches.sent': 'Enviadas',
    'dispatches.deleteConfirm': 'Tem certeza que deseja deletar este disparo?',
    'dispatches.deleteTemplateConfirm': 'Tem certeza que deseja deletar este template?',
    // Dispatch Creator
    'dispatchCreator.title': 'Criar Disparo',
    'dispatchCreator.dispatchName': 'Nome do Disparo',
    'dispatchCreator.dispatchNamePlaceholder': 'Ex: Campanha Janeiro 2025',
    'dispatchCreator.instance': 'Instância do WhatsApp',
    'dispatchCreator.selectInstance': 'Selecione uma instância',
    'dispatchCreator.template': 'Template',
    'dispatchCreator.selectTemplate': 'Selecione um template',
    'dispatchCreator.next': 'Próximo',
    'dispatchCreator.back': 'Voltar',
    'dispatchCreator.cancel': 'Cancelar',
    'dispatchCreator.create': 'Criar Disparo',
    'dispatchCreator.creating': 'Criando...',
    'dispatchCreator.contactSource': 'Fonte de Contatos',
    'dispatchCreator.contactList': 'Lista de Contatos',
    'dispatchCreator.kanbanColumns': 'Colunas do Kanban',
    'dispatchCreator.csvUpload': 'Upload de CSV',
    'dispatchCreator.noFileChosen': 'Nenhum arquivo escolhido',
    'dispatchCreator.pasteContacts': 'Ou cole os contatos (formato: nome;número ou apenas número)',
    'dispatchCreator.processText': 'Processar Texto',
    'dispatchCreator.contactsProcessed': 'contato(s) processado(s)',
    'dispatchCreator.validateContacts': 'Validar Contatos',
    'dispatchCreator.validating': 'Validando...',
    'dispatchCreator.selectColumns': 'Selecione as Colunas',
    'dispatchCreator.speed': 'Velocidade do Disparo',
    'dispatchCreator.speedFast': 'Rápido (1 segundo) - Listas pequenas',
    'dispatchCreator.speedNormal': 'Normal (30 segundos) - Recomendado',
    'dispatchCreator.speedSlow': 'Lento (1 minuto) - Mais seguro',
    'dispatchCreator.speedRandomized': 'Randomizado (55-85 segundos) - Anti-detecção',
    'dispatchCreator.autoDelete': 'Excluir mensagem automaticamente para todos',
    'dispatchCreator.deleteDelay': 'Delay',
    'dispatchCreator.deleteDelayUnit': 'Unidade',
    'dispatchCreator.seconds': 'Segundos',
    'dispatchCreator.minutes': 'Minutos',
    'dispatchCreator.hours': 'Horas',
    'dispatchCreator.defaultName': 'Nome Padrão para Personalização',
    'dispatchCreator.defaultNamePlaceholder': 'Cliente',
    'dispatchCreator.defaultNameHelp': 'Usado quando não houver nome do contato',
    'dispatchCreator.schedule': 'Agendar disparo',
    'dispatchCreator.startTime': 'Horário de Início',
    'dispatchCreator.endTime': 'Horário de Pausa',
    'dispatchCreator.suspendedDays': 'Dias Suspensos',
    'dispatchCreator.days': ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
    // Template Builder
    'templateBuilder.title': 'Criar Template',
    'templateBuilder.editTitle': 'Editar Template',
    'templateBuilder.templateName': 'Nome do Template',
    'templateBuilder.templateNamePlaceholder': 'Ex: Boas-vindas',
    'templateBuilder.templateType': 'Tipo de Template',
    'templateBuilder.configure': 'Configurar',
    'templateBuilder.back': 'Voltar',
    'templateBuilder.cancel': 'Cancelar',
    'templateBuilder.save': 'Salvar Template',
    'templateBuilder.saving': 'Salvando...',
    'templateBuilder.types.text': 'Texto',
    'templateBuilder.types.image': 'Imagem',
    'templateBuilder.types.imageCaption': 'Imagem com Legenda',
    'templateBuilder.types.video': 'Vídeo',
    'templateBuilder.types.videoCaption': 'Vídeo com Legenda',
    'templateBuilder.types.audio': 'Áudio',
    'templateBuilder.types.file': 'Arquivo',
    'templateBuilder.types.sequence': 'Sequência de Mensagens',
    'templateBuilder.textMessage': 'Mensagem de Texto',
    'templateBuilder.imageUrl': 'URL da Imagem',
    'templateBuilder.imageUrlPlaceholder': 'https://exemplo.com/imagem.jpg',
    'templateBuilder.videoUrl': 'URL do Vídeo',
    'templateBuilder.videoUrlPlaceholder': 'https://exemplo.com/video.mp4',
    'templateBuilder.audioUrl': 'URL do Áudio',
    'templateBuilder.audioUrlPlaceholder': 'https://exemplo.com/audio.mp3',
    'templateBuilder.fileUrl': 'URL do Arquivo',
    'templateBuilder.fileUrlPlaceholder': 'https://exemplo.com/arquivo.pdf',
    'templateBuilder.fileName': 'Nome do Arquivo',
    'templateBuilder.fileNamePlaceholder': 'documento.pdf',
    'templateBuilder.caption': 'Legenda',
    'templateBuilder.messagePlaceholder': 'Digite sua mensagem aqui...',
    'templateBuilder.captionPlaceholder': 'Digite a legenda aqui...',
    'templateBuilder.sequenceDescription': 'Crie uma sequência de mensagens. Mínimo 2 etapas de tipos distintos.',
    'templateBuilder.sequenceMinSteps': 'Sequência deve ter no mínimo 2 etapas',
    'templateBuilder.sequenceDistinctTypes': 'Sequência deve ter pelo menos 2 etapas de tipos distintos',
    'templateBuilder.step': 'Etapa',
    'templateBuilder.stepType': 'Tipo',
    'templateBuilder.remove': 'Remover',
    'templateBuilder.addStep': '+ Adicionar Etapa',
    'templateBuilder.delay': 'Delay',
    'templateBuilder.delayUnit': 'Unidade',
    'templateBuilder.message': 'Mensagem',
    'templateBuilder.digiteMensagem': 'Digite sua mensagem...',
    'templateBuilder.digiteLegenda': 'Digite a legenda...',
    'templateBuilder.uploadFile': 'Fazer Upload de Arquivo',
    'templateBuilder.selectFile': 'Selecionar Arquivo',
    'templateBuilder.uploading': 'Enviando...',
    'templateBuilder.fileSelected': 'Arquivo selecionado',
    'templateBuilder.or': 'ou',
    // MindClerky
    'mindClerky.title': 'MindClerky',
    'mindClerky.subtitle': 'Crie e gerencie workflows visuais com Flow-Based Programming',
    'mindClerky.createWorkflow': 'Criar Workflow',
    'mindClerky.createNewWorkflow': 'Criar Novo Workflow',
    'mindClerky.workflowName': 'Nome do Workflow',
    'mindClerky.workflowNamePlaceholder': 'Ex: Atendimento Automático',
    'mindClerky.save': 'Salvar',
    'mindClerky.saving': 'Salvando...',
    'mindClerky.cancel': 'Cancelar',
    'mindClerky.delete': 'Deletar',
    'mindClerky.deleteConfirm': 'Tem certeza que deseja deletar este workflow?',
    'mindClerky.edit': 'Editar',
    'mindClerky.noWorkflows': 'Nenhum workflow criado ainda',
    'mindClerky.noWorkflowsDescription': 'Crie seu primeiro workflow para começar a automatizar processos.',
    'mindClerky.loading': 'Carregando workflows...',
    'mindClerky.nodes': 'Nós',
    'mindClerky.nodes.trigger': 'Gatilho WhatsApp',
    'mindClerky.nodes.typebotTrigger': 'Gatilho Typebot',
    'mindClerky.nodes.condition': 'Condição',
    'mindClerky.nodes.delay': 'Delay',
    'mindClerky.nodes.end': 'Fim de Fluxo',
    'mindClerky.nodes.response': 'Resposta WhatsApp',
    'mindClerky.nodes.spreadsheet': 'Planilha Google',
    'mindClerky.nodes.openai': 'OpenAI',
    'mindClerky.nodes.trigger.description': 'Inicia o workflow quando recebe uma mensagem',
    'mindClerky.nodes.typebotTrigger.description': 'Inicia o workflow quando recebe um webhook do Typebot',
    'mindClerky.nodes.spreadsheet.description': 'Cria e atualiza planilhas no Google Sheets',
    'mindClerky.nodes.condition.description': 'Verifica condições no texto da mensagem',
    'mindClerky.nodes.delay.description': 'Adiciona um tempo de espera',
    'mindClerky.nodes.end.description': 'Finaliza a execução do workflow',
    'mindClerky.nodes.response.description': 'Envia uma resposta via WhatsApp',
    'mindClerky.nodes.openai.description': 'Processa mensagens usando inteligência artificial da OpenAI',
    'mindClerky.nodeSettings': 'Configurações do Nó',
    'mindClerky.nodeSettings.instance': 'Instância',
    'mindClerky.nodeSettings.selectInstance': 'Selecione uma instância',
    'mindClerky.nodeSettings.conditions': 'Condições',
    'mindClerky.nodeSettings.addCondition': 'Adicionar Condição',
    'mindClerky.nodeSettings.removeCondition': 'Remover',
    'mindClerky.nodeSettings.conditionText': 'Texto da Condição',
    'mindClerky.nodeSettings.conditionPlaceholder': 'Ex: olá, ajuda, suporte',
    'mindClerky.nodeSettings.delay': 'Tempo de Espera',
    'mindClerky.nodeSettings.delayValue': 'Valor',
    'mindClerky.nodeSettings.delayUnit': 'Unidade',
    'mindClerky.nodeSettings.delaySeconds': 'Segundos',
    'mindClerky.nodeSettings.delayMinutes': 'Minutos',
    'mindClerky.nodeSettings.delayHours': 'Horas',
    'mindClerky.nodeSettings.responseType': 'Tipo de Resposta',
    'mindClerky.nodeSettings.configureResponse': 'Configure a resposta',
    'mindClerky.nodeSettings.webhookUrl': 'URL do Webhook',
    'mindClerky.nodeSettings.webhookUrlDescription': 'Use esta URL no Typebot para enviar dados ao workflow',
    'mindClerky.nodeSettings.webhookUrlCopied': 'URL copiada para a área de transferência!',
    'mindClerky.nodeSettings.copy': 'Copiar',
    'mindClerky.nodeSettings.configureWebhook': 'Configurar webhook',
    'mindClerky.nodeSettings.authenticateGoogle': 'Autenticar com Google',
    'mindClerky.nodeSettings.authenticateGoogleDescription': 'Clique para fazer login com sua conta Google e permitir acesso às planilhas',
    'mindClerky.nodeSettings.authenticated': 'Autenticado com sucesso',
    'mindClerky.nodeSettings.spreadsheetName': 'Nome da Planilha',
    'mindClerky.nodeSettings.spreadsheetNamePlaceholder': 'Ex: Dados Typebot',
    'mindClerky.nodeSettings.sheetName': 'Nome da Aba',
    'mindClerky.nodeSettings.sheetNamePlaceholder': 'Ex: Planilha1',
    'mindClerky.nodeSettings.sheet': 'Aba',
    'mindClerky.nodeSettings.spreadsheetId': 'ID da Planilha',
    'mindClerky.nodeSettings.openaiApiKey': 'Chave API OpenAI',
    'mindClerky.nodeSettings.openaiApiKeyPlaceholder': 'sk-...',
    'mindClerky.nodeSettings.openaiApiKeyDescription': 'Sua chave API da OpenAI (mantida segura)',
    'mindClerky.nodeSettings.openaiModel': 'Modelo',
    'mindClerky.nodeSettings.openaiPrompt': 'Prompt',
    'mindClerky.nodeSettings.openaiPromptPlaceholder': 'Você é um assistente útil. Responda à mensagem do usuário: {message}',
    'mindClerky.nodeSettings.openaiPromptDescription': 'Use {message} para incluir a mensagem recebida do WhatsApp',
    'mindClerky.nodeSettings.variablesHelp': 'Ajuda sobre variáveis',
    'mindClerky.nodeSettings.variablesModalTitle': 'Variáveis do Typebot',
    'mindClerky.nodeSettings.variablesModalDescription': 'Você pode usar variáveis do Typebot no seu prompt para criar funis personalizados. As variáveis são automaticamente substituídas pelos valores recebidos do webhook do Typebot.',
    'mindClerky.nodeSettings.variablesFromTypebot': 'Variáveis do Typebot',
    'mindClerky.nodeSettings.variablesFromTypebotDescription': 'As variáveis disponíveis são as mesmas que você criou no seu formulário do Typebot. Elas são capturadas automaticamente quando o webhook é recebido.',
    'mindClerky.nodeSettings.availableVariables': 'Variáveis Disponíveis',
    'mindClerky.nodeSettings.variableNameDescription': 'Nome do contato (campo "Name" do Typebot)',
    'mindClerky.nodeSettings.variableTelefoneDescription': 'Telefone do contato (campo "Telefone" do Typebot)',
    'mindClerky.nodeSettings.variableIdadeDescription': 'Idade do contato (campo "Idade" do Typebot)',
    'mindClerky.nodeSettings.variableSubmittedAtDescription': 'Data e hora do envio do formulário (campo "submittedAt" do Typebot)',
    'mindClerky.nodeSettings.note': 'Nota',
    'mindClerky.nodeSettings.variablesNote': 'Todas as variáveis do Typebot podem ser usadas no prompt. Basta usar o nome do campo com o prefixo $ (ex: $Name, $Telefone, $Idade).',
    'mindClerky.nodeSettings.example': 'Exemplo',
    'mindClerky.nodeSettings.examplePrompt': 'Olá $Name! Você tem $Idade anos e seu telefone é $Telefone. Como posso ajudá-lo hoje?',
    'mindClerky.nodeSettings.configureOpenAI': 'Configure a OpenAI',
    'mindClerky.contacts': 'Contatos',
    'mindClerky.contacts.title': 'Contatos que Entraram no Workflow',
    'mindClerky.contacts.clear': 'Limpar Lista',
    'mindClerky.contacts.clearing': 'Limpando...',
    'mindClerky.contacts.clearConfirm': 'Tem certeza que deseja limpar a lista de contatos?',
    'mindClerky.contacts.clearSuccess': 'Lista de contatos limpa com sucesso!',
    'mindClerky.contacts.empty': 'Nenhum contato entrou neste workflow ainda',
    'mindClerky.contacts.phone': 'Telefone',
    'mindClerky.contacts.enteredAt': 'Entrou em',
    'mindClerky.canvas': 'Canvas',
    'mindClerky.canvas.zoomIn': 'Aumentar Zoom',
    'mindClerky.canvas.zoomOut': 'Diminuir Zoom',
    'mindClerky.canvas.fitView': 'Ajustar Visualização',
    'mindClerky.canvas.reset': 'Resetar',
  },
  en: {
    // Login
    'login.title': 'Login',
    'login.welcome': 'Welcome back',
    'login.subtitle': 'Sign in with your credentials to continue',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.emailPlaceholder': 'your@email.com',
    'login.passwordPlaceholder': '••••••••',
    'login.forgotPassword': 'Forgot password?',
    'login.submit': 'Sign in',
    'login.submitting': 'Signing in...',
    'login.noAccount': "Don't have an account?",
    'login.signUp': 'Sign up',
    // Sign Up
    'signup.title': 'Create account',
    'signup.subtitle': 'Fill in the information below to create your account',
    'signup.name': 'Full name',
    'signup.namePlaceholder': 'Your full name',
    'signup.confirmPassword': 'Confirm password',
    'signup.confirmPasswordPlaceholder': 'Enter password again',
    'signup.terms': 'I accept the',
    'signup.termsOfUse': 'terms of use',
    'signup.and': 'and',
    'signup.privacyPolicy': 'privacy policy',
    'signup.submit': 'Create account',
    'signup.submitting': 'Creating account...',
    'signup.hasAccount': 'Already have an account?',
    'signup.signIn': 'Sign in',
    // Validation
    'validation.emailRequired': 'Email is required',
    'validation.emailInvalid': 'Invalid email',
    'validation.passwordRequired': 'Password is required',
    'validation.passwordMinLength': 'Password must be at least 6 characters',
    'validation.nameRequired': 'Name is required',
    'validation.nameMinLength': 'Name must be at least 3 characters',
    'validation.confirmPasswordRequired': 'Password confirmation is required',
    'validation.passwordsNotMatch': 'Passwords do not match',
    'validation.termsRequired': 'You must accept the terms of use',
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome, {name}!',
    'dashboard.email': 'Email',
    'dashboard.logout': 'Logout',
    'dashboard.successMessage': 'You are successfully logged in. This is an example dashboard page.',
    // Menu
    'menu.home': 'Home',
    'menu.connectionManager': 'Instances',
    'menu.dispatches': 'Dispatches',
    'menu.crm': 'CRM',
    'menu.mindClerky': 'MindClerky',
    'menu.integration': 'Integration',
    'menu.aiAgent': 'AI Agent',
    'menu.documentation': 'Documentation',
    'menu.settings': 'Settings',
    'menu.logout': 'Logout',
    // Common
    'common.appName': 'Clerky',
    'common.comingSoon': 'Coming soon...',
    'common.loading': 'Loading...',
    // CRM
    'crm.searchContacts': 'Search contacts...',
    'crm.dragContactsHere': 'Drag contacts here',
    'crm.contact': 'contact',
    'crm.contacts': 'contacts',
    // Settings
    'settings.title': 'Settings',
    'settings.profile': 'Profile',
    'settings.profilePicture': 'Profile Picture',
    'settings.changePicture': 'Change Picture',
    'settings.removePicture': 'Remove Picture',
    'settings.name': 'Name',
    'settings.namePlaceholder': 'Your full name',
    'settings.email': 'Email',
    'settings.companyName': 'Company Name',
    'settings.companyNamePlaceholder': 'Your company name',
    'settings.phone': 'Phone',
    'settings.phonePlaceholder': '(DDD) 9 9999-9999',
    'settings.saveProfile': 'Save Profile',
    'settings.saving': 'Saving...',
    'settings.profileUpdated': 'Profile updated successfully!',
    'settings.password': 'Password',
    'settings.changePassword': 'Change Password',
    'settings.currentPassword': 'Current Password',
    'settings.currentPasswordPlaceholder': 'Enter your current password',
    'settings.newPassword': 'New Password',
    'settings.newPasswordPlaceholder': 'Enter new password',
    'settings.confirmNewPassword': 'Confirm New Password',
    'settings.confirmNewPasswordPlaceholder': 'Enter new password again',
    'settings.updatePassword': 'Update Password',
    'settings.updating': 'Updating...',
    'settings.passwordUpdated': 'Password changed successfully!',
    'settings.selectImage': 'Select Image',
    'settings.imageTooLarge': 'Image must be at most 2MB',
    'settings.invalidImageFormat': 'Invalid image format. Use JPG, PNG or GIF',
    'settings.cropImage': 'Crop Image',
    'settings.cropInstructions': 'Drag to move the crop area. Use controls for zoom and rotation.',
    'settings.applyCrop': 'Apply Crop',
    'settings.zoomIn': 'Zoom In',
    'settings.zoomOut': 'Zoom Out',
    'settings.rotateLeft': 'Rotate Left',
    'settings.rotateRight': 'Rotate Right',
    'settings.preview': 'Preview',
    'common.cancel': 'Cancel',
    // Errors
    'error.loginFailed': 'Error logging in. Check your credentials.',
    'error.registerFailed': 'Error creating account. Please try again.',
    'error.formProcessing': 'Error processing form',
    'error.requestFailed': 'Error processing request. Please try again.',
    'error.updateProfileFailed': 'Error updating profile. Please try again.',
    'error.changePasswordFailed': 'Error changing password. Check the data and try again.',
    'error.getInstancesFailed': 'Error fetching instances. Please try again.',
    'error.createInstanceFailed': 'Error creating instance. Please try again.',
    'error.deleteInstanceFailed': 'Error deleting instance. Please try again.',
    'error.updateSettingsFailed': 'Error updating settings. Please try again.',
    // Instances
    'instances.title': 'WhatsApp Instances',
    'instances.create': 'Create Instance',
    'instances.createNew': 'Create New Instance',
    'instances.createButton': 'Create',
    'instances.creating': 'Creating...',
    'instances.cancel': 'Cancel',
    'instances.name': 'Name',
    'instances.instanceName': 'Instance Name',
    'instances.instanceNamePlaceholder': 'Ex: Personal WhatsApp, Business WhatsApp...',
    'instances.instanceNameHelp': 'Choose a name to identify this instance (minimum 3 characters)',
    'instances.internalName': 'Internal Name',
    'instances.qrcode': 'QR Code',
    'instances.settings': 'Settings',
    'instances.updateSettings': 'Update Settings',
    'instances.updateButton': 'Update',
    'instances.updating': 'Updating...',
    'instances.checkStatus': 'Check Status',
    'instances.delete': 'Delete',
    'instances.deleteConfirm': 'Are you sure you want to delete this instance?',
    'instances.deleteSuccess': 'Instance deleted successfully!',
    'instances.createSuccess': 'Instance created successfully!',
    'instances.settingsUpdated': 'Settings updated successfully!',
    'instances.statusChecked': 'Status checked!',
    'instances.noInstances': 'No instances found',
    'instances.noInstancesDescription': 'Create your first WhatsApp instance to get started.',
    'instances.scanQRCode': 'Scan the QR Code with your WhatsApp',
    'instances.qrCodeAutoClose': 'The modal will close automatically when the connection is established.',
    'instances.connectedSuccess': 'Instance connected successfully!',
    'instances.rejectCall': 'Reject calls',
    'instances.groupsIgnore': 'Ignore groups',
    'instances.alwaysOnline': 'Always online',
    'instances.readMessages': 'Mark messages as read',
    'instances.readStatus': 'Read status',
    'instances.syncFullHistory': 'Sync full history',
    'instances.created': 'Created',
    'instances.connecting': 'Connecting',
    'instances.connected': 'Connected',
    'instances.disconnected': 'Disconnected',
    'instances.error': 'Error',
    // Dispatches
    'dispatches.title': 'Dispatches',
    'dispatches.subtitle': 'Manage templates and mass message dispatches',
    'dispatches.templates': 'Templates',
    'dispatches.dispatches': 'Dispatches',
    'dispatches.createTemplate': 'Create Template',
    'dispatches.createFirstTemplate': 'Create First Template',
    'dispatches.createDispatch': 'Create Dispatch',
    'dispatches.createFirstDispatch': 'Create First Dispatch',
    'dispatches.myTemplates': 'My Templates',
    'dispatches.myDispatches': 'My Dispatches',
    'dispatches.noTemplates': 'No templates created yet',
    'dispatches.noDispatches': 'No dispatches created yet',
    'dispatches.loadingTemplates': 'Loading templates...',
    'dispatches.loadingDispatches': 'Loading dispatches...',
    'dispatches.type': 'Type',
    'dispatches.edit': 'Edit',
    'dispatches.delete': 'Delete',
    'dispatches.pause': 'Pause',
    'dispatches.resume': 'Resume',
    'dispatches.start': 'Start',
    'dispatches.status': 'Status',
    'dispatches.sent': 'Sent',
    'dispatches.deleteConfirm': 'Are you sure you want to delete this dispatch?',
    'dispatches.deleteTemplateConfirm': 'Are you sure you want to delete this template?',
    // Dispatch Creator
    'dispatchCreator.title': 'Create Dispatch',
    'dispatchCreator.dispatchName': 'Dispatch Name',
    'dispatchCreator.dispatchNamePlaceholder': 'Ex: January 2025 Campaign',
    'dispatchCreator.instance': 'WhatsApp Instance',
    'dispatchCreator.selectInstance': 'Select an instance',
    'dispatchCreator.template': 'Template',
    'dispatchCreator.selectTemplate': 'Select a template',
    'dispatchCreator.next': 'Next',
    'dispatchCreator.back': 'Back',
    'dispatchCreator.cancel': 'Cancel',
    'dispatchCreator.create': 'Create Dispatch',
    'dispatchCreator.creating': 'Creating...',
    'dispatchCreator.contactSource': 'Contact Source',
    'dispatchCreator.contactList': 'Contact List',
    'dispatchCreator.kanbanColumns': 'Kanban Columns',
    'dispatchCreator.csvUpload': 'CSV Upload',
    'dispatchCreator.noFileChosen': 'No file chosen',
    'dispatchCreator.pasteContacts': 'Or paste contacts (format: name;number or just number)',
    'dispatchCreator.processText': 'Process Text',
    'dispatchCreator.contactsProcessed': 'contact(s) processed',
    'dispatchCreator.validateContacts': 'Validate Contacts',
    'dispatchCreator.validating': 'Validating...',
    'dispatchCreator.selectColumns': 'Select Columns',
    'dispatchCreator.speed': 'Dispatch Speed',
    'dispatchCreator.speedFast': 'Fast (1 second) - Small lists',
    'dispatchCreator.speedNormal': 'Normal (30 seconds) - Recommended',
    'dispatchCreator.speedSlow': 'Slow (1 minute) - Safer',
    'dispatchCreator.speedRandomized': 'Randomized (55-85 seconds) - Anti-detection',
    'dispatchCreator.autoDelete': 'Automatically delete message for everyone',
    'dispatchCreator.deleteDelay': 'Delay',
    'dispatchCreator.deleteDelayUnit': 'Unit',
    'dispatchCreator.seconds': 'Seconds',
    'dispatchCreator.minutes': 'Minutes',
    'dispatchCreator.hours': 'Hours',
    'dispatchCreator.defaultName': 'Default Name for Personalization',
    'dispatchCreator.defaultNamePlaceholder': 'Client',
    'dispatchCreator.defaultNameHelp': 'Used when contact has no name',
    'dispatchCreator.schedule': 'Schedule dispatch',
    'dispatchCreator.startTime': 'Start Time',
    'dispatchCreator.endTime': 'Pause Time',
    'dispatchCreator.suspendedDays': 'Suspended Days',
    'dispatchCreator.days': ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    // Template Builder
    'templateBuilder.title': 'Create Template',
    'templateBuilder.editTitle': 'Edit Template',
    'templateBuilder.templateName': 'Template Name',
    'templateBuilder.templateNamePlaceholder': 'Ex: Welcome',
    'templateBuilder.templateType': 'Template Type',
    'templateBuilder.configure': 'Configure',
    'templateBuilder.back': 'Back',
    'templateBuilder.cancel': 'Cancel',
    'templateBuilder.save': 'Save Template',
    'templateBuilder.saving': 'Saving...',
    'templateBuilder.types.text': 'Text',
    'templateBuilder.types.image': 'Image',
    'templateBuilder.types.imageCaption': 'Image with Caption',
    'templateBuilder.types.video': 'Video',
    'templateBuilder.types.videoCaption': 'Video with Caption',
    'templateBuilder.types.audio': 'Audio',
    'templateBuilder.types.file': 'File',
    'templateBuilder.types.sequence': 'Message Sequence',
    'templateBuilder.textMessage': 'Text Message',
    'templateBuilder.imageUrl': 'Image URL',
    'templateBuilder.imageUrlPlaceholder': 'https://example.com/image.jpg',
    'templateBuilder.videoUrl': 'Video URL',
    'templateBuilder.videoUrlPlaceholder': 'https://example.com/video.mp4',
    'templateBuilder.audioUrl': 'Audio URL',
    'templateBuilder.audioUrlPlaceholder': 'https://example.com/audio.mp3',
    'templateBuilder.fileUrl': 'File URL',
    'templateBuilder.fileUrlPlaceholder': 'https://example.com/file.pdf',
    'templateBuilder.fileName': 'File Name',
    'templateBuilder.fileNamePlaceholder': 'document.pdf',
    'templateBuilder.caption': 'Caption',
    'templateBuilder.messagePlaceholder': 'Type your message here...',
    'templateBuilder.captionPlaceholder': 'Type the caption here...',
    'templateBuilder.sequenceDescription': 'Create a sequence of messages. Minimum 2 steps of distinct types.',
    'templateBuilder.sequenceMinSteps': 'Sequence must have at least 2 steps',
    'templateBuilder.sequenceDistinctTypes': 'Sequence must have at least 2 steps of distinct types',
    'templateBuilder.step': 'Step',
    'templateBuilder.stepType': 'Type',
    'templateBuilder.remove': 'Remove',
    'templateBuilder.addStep': '+ Add Step',
    'templateBuilder.delay': 'Delay',
    'templateBuilder.delayUnit': 'Unit',
    'templateBuilder.message': 'Message',
    'templateBuilder.digiteMensagem': 'Type your message...',
    'templateBuilder.digiteLegenda': 'Type the caption...',
    'templateBuilder.uploadFile': 'Upload File',
    'templateBuilder.selectFile': 'Select File',
    'templateBuilder.uploading': 'Uploading...',
    'templateBuilder.fileSelected': 'File selected',
    'templateBuilder.or': 'or',
    // MindClerky
    'mindClerky.title': 'MindClerky',
    'mindClerky.subtitle': 'Create and manage visual workflows with Flow-Based Programming',
    'mindClerky.createWorkflow': 'Create Workflow',
    'mindClerky.createNewWorkflow': 'Create New Workflow',
    'mindClerky.workflowName': 'Workflow Name',
    'mindClerky.workflowNamePlaceholder': 'Ex: Automatic Support',
    'mindClerky.save': 'Save',
    'mindClerky.saving': 'Saving...',
    'mindClerky.cancel': 'Cancel',
    'mindClerky.delete': 'Delete',
    'mindClerky.deleteConfirm': 'Are you sure you want to delete this workflow?',
    'mindClerky.edit': 'Edit',
    'mindClerky.noWorkflows': 'No workflows created yet',
    'mindClerky.noWorkflowsDescription': 'Create your first workflow to start automating processes.',
    'mindClerky.loading': 'Loading workflows...',
    'mindClerky.nodes': 'Nodes',
    'mindClerky.nodes.trigger': 'WhatsApp Trigger',
    'mindClerky.nodes.typebotTrigger': 'Typebot Trigger',
    'mindClerky.nodes.condition': 'Condition',
    'mindClerky.nodes.delay': 'Delay',
    'mindClerky.nodes.end': 'End Flow',
    'mindClerky.nodes.response': 'WhatsApp Response',
    'mindClerky.nodes.spreadsheet': 'Google Spreadsheet',
    'mindClerky.nodes.openai': 'OpenAI',
    'mindClerky.nodes.trigger.description': 'Starts the workflow when receiving a message',
    'mindClerky.nodes.typebotTrigger.description': 'Starts the workflow when receiving a Typebot webhook',
    'mindClerky.nodes.spreadsheet.description': 'Creates and updates Google Sheets spreadsheets',
    'mindClerky.nodes.condition.description': 'Checks conditions in the message text',
    'mindClerky.nodes.delay.description': 'Adds a waiting time',
    'mindClerky.nodes.end.description': 'Ends the workflow execution',
    'mindClerky.nodes.response.description': 'Sends a WhatsApp message response',
    'mindClerky.nodes.openai.description': 'Processes messages using OpenAI artificial intelligence',
    'mindClerky.nodeSettings': 'Node Settings',
    'mindClerky.nodeSettings.instance': 'Instance',
    'mindClerky.nodeSettings.selectInstance': 'Select an instance',
    'mindClerky.nodeSettings.conditions': 'Conditions',
    'mindClerky.nodeSettings.addCondition': 'Add Condition',
    'mindClerky.nodeSettings.removeCondition': 'Remove',
    'mindClerky.nodeSettings.conditionText': 'Condition Text',
    'mindClerky.nodeSettings.conditionPlaceholder': 'Ex: hello, help, support',
    'mindClerky.nodeSettings.delay': 'Wait Time',
    'mindClerky.nodeSettings.delayValue': 'Value',
    'mindClerky.nodeSettings.delayUnit': 'Unit',
    'mindClerky.nodeSettings.delaySeconds': 'Seconds',
    'mindClerky.nodeSettings.delayMinutes': 'Minutes',
    'mindClerky.nodeSettings.delayHours': 'Hours',
    'mindClerky.nodeSettings.responseType': 'Response Type',
    'mindClerky.nodeSettings.configureResponse': 'Configure the response',
    'mindClerky.nodeSettings.webhookUrl': 'Webhook URL',
    'mindClerky.nodeSettings.webhookUrlDescription': 'Use this URL in Typebot to send data to the workflow',
    'mindClerky.nodeSettings.webhookUrlCopied': 'URL copied to clipboard!',
    'mindClerky.nodeSettings.copy': 'Copy',
    'mindClerky.nodeSettings.configureWebhook': 'Configure webhook',
    'mindClerky.nodeSettings.authenticateGoogle': 'Authenticate with Google',
    'mindClerky.nodeSettings.authenticateGoogleDescription': 'Click to sign in with your Google account and allow access to spreadsheets',
    'mindClerky.nodeSettings.authenticated': 'Successfully authenticated',
    'mindClerky.nodeSettings.spreadsheetName': 'Spreadsheet Name',
    'mindClerky.nodeSettings.spreadsheetNamePlaceholder': 'Ex: Typebot Data',
    'mindClerky.nodeSettings.sheetName': 'Sheet Name',
    'mindClerky.nodeSettings.sheetNamePlaceholder': 'Ex: Sheet1',
    'mindClerky.nodeSettings.sheet': 'Sheet',
    'mindClerky.nodeSettings.spreadsheetId': 'Spreadsheet ID',
    'mindClerky.nodeSettings.openaiApiKey': 'OpenAI API Key',
    'mindClerky.nodeSettings.openaiApiKeyPlaceholder': 'sk-...',
    'mindClerky.nodeSettings.openaiApiKeyDescription': 'Your OpenAI API key (kept secure)',
    'mindClerky.nodeSettings.openaiModel': 'Model',
    'mindClerky.nodeSettings.openaiPrompt': 'Prompt',
    'mindClerky.nodeSettings.openaiPromptPlaceholder': 'You are a helpful assistant. Respond to the user message: {message}',
    'mindClerky.nodeSettings.openaiPromptDescription': 'Use {message} to include the received WhatsApp message',
    'mindClerky.nodeSettings.variablesHelp': 'Help about variables',
    'mindClerky.nodeSettings.variablesModalTitle': 'Typebot Variables',
    'mindClerky.nodeSettings.variablesModalDescription': 'You can use Typebot variables in your prompt to create personalized funnels. Variables are automatically replaced by values received from the Typebot webhook.',
    'mindClerky.nodeSettings.variablesFromTypebot': 'Typebot Variables',
    'mindClerky.nodeSettings.variablesFromTypebotDescription': 'Available variables are the same ones you created in your Typebot form. They are automatically captured when the webhook is received.',
    'mindClerky.nodeSettings.availableVariables': 'Available Variables',
    'mindClerky.nodeSettings.variableNameDescription': 'Contact name (Typebot "Name" field)',
    'mindClerky.nodeSettings.variableTelefoneDescription': 'Contact phone (Typebot "Telefone" field)',
    'mindClerky.nodeSettings.variableIdadeDescription': 'Contact age (Typebot "Idade" field)',
    'mindClerky.nodeSettings.variableSubmittedAtDescription': 'Form submission date and time (Typebot "submittedAt" field)',
    'mindClerky.nodeSettings.note': 'Note',
    'mindClerky.nodeSettings.variablesNote': 'All Typebot variables can be used in the prompt. Just use the field name with the $ prefix (e.g., $Name, $Telefone, $Idade).',
    'mindClerky.nodeSettings.example': 'Example',
    'mindClerky.nodeSettings.examplePrompt': 'Hello $Name! You are $Idade years old and your phone is $Telefone. How can I help you today?',
    'mindClerky.nodeSettings.configureOpenAI': 'Configure OpenAI',
    'mindClerky.contacts': 'Contacts',
    'mindClerky.contacts.title': 'Contacts that Entered the Workflow',
    'mindClerky.contacts.clear': 'Clear List',
    'mindClerky.contacts.clearing': 'Clearing...',
    'mindClerky.contacts.clearConfirm': 'Are you sure you want to clear the contacts list?',
    'mindClerky.contacts.clearSuccess': 'Contacts list cleared successfully!',
    'mindClerky.contacts.empty': 'No contacts have entered this workflow yet',
    'mindClerky.contacts.phone': 'Phone',
    'mindClerky.contacts.enteredAt': 'Entered at',
    'mindClerky.canvas': 'Canvas',
    'mindClerky.canvas.zoomIn': 'Zoom In',
    'mindClerky.canvas.zoomOut': 'Zoom Out',
    'mindClerky.canvas.fitView': 'Fit View',
    'mindClerky.canvas.reset': 'Reset',
  },
};

// Função auxiliar para substituir placeholders em traduções
export const translateWithParams = (text: string, params: Record<string, string>): string => {
  let translated = text;
  Object.entries(params).forEach(([key, value]) => {
    translated = translated.replace(`{${key}}`, value);
  });
  return translated;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Tentar recuperar idioma salvo no localStorage
    const savedLanguage = localStorage.getItem('language') as Language;
    return savedLanguage || 'pt';
  });

  const t = (key: string, params?: Record<string, string>): string => {
    const translation = translations[language][key as keyof typeof translations.pt] || key;
    
    // Se for um array, retornar a primeira string ou string vazia
    if (Array.isArray(translation)) {
      return translation[0] || '';
    }
    
    // Se houver parâmetros, substituir placeholders
    if (params) {
      return translateWithParams(translation as string, params);
    }
    
    return translation as string;
  };

  const tArray = (key: string): string[] => {
    const translation = translations[language][key as keyof typeof translations.pt] || key;
    
    // Se for um array, retornar como está
    if (Array.isArray(translation)) {
      return translation;
    }
    
    // Se não for array, retornar array com a string
    return [translation as string];
  };

  const setLanguageWithStorage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: setLanguageWithStorage, t, tArray }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

